substitutions:
  name: "m5-dial"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  project:
    name: smarthomeyourself.m5_dial
    version: "1.0"
    
  platformio_options:
    lib_deps:
      - WiFi
      - SPI
      - FS
      - Wire
      - EEPROM
      - ArduinoJson
      - m5stack/M5Unified@0.1.14
      - m5stack/M5Dial

external_components:
  - source:
      type: git
      url: https://github.com/jnalley20/m5-dial-for-esphome/
      ref: patch-1
    components: [shys_m5_dial]
 
dashboard_import:
  package_import_url: github://SmartHome-yourself/jnalley20/shys-m5-dial.yaml@patch-1
  import_full_config: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

improv_serial:

i2c:
  - id: internal_i2c
    sda: GPIO11
    scl: GPIO12

rc522_i2c:
  - id: nfc_reader
    i2c_id: internal_i2c
    address: 0x28

output:
  - platform: ledc
    pin: GPIO3
    id: buzzer

rtttl:
  output: buzzer