substitutions:
  name: "m5-dial"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password  

esphome:
  name: ${name}
  name_add_mac_suffix: false
  project:
    name: smarthomeyourself.m5_dial
    version: "1.0"
    
  platformio_options:
    lib_deps:
      - WiFi
      - SPI
      - FS
      - Wire
      - EEPROM
      - ArduinoJson
      - m5stack/M5Unified@0.1.14
      - m5stack/M5Dial

external_components:
  - source:
      type: git
      url: https://github.com/jnalley20/m5-dial-for-esphome/
      ref: main
    components: [shys_m5_dial]
 
dashboard_import:
  package_import_url: github://jnalley20/m5-dial-for-esphome/shys-m5-dial.yaml@main
  import_full_config: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

improv_serial:

i2c:
  - id: internal_i2c
    sda: GPIO11
    scl: GPIO12

rc522_i2c:
  - id: nfc_reader
    i2c_id: internal_i2c
    address: 0x28
